all:
	python train.py
	echo 'Trained ~!'

clean_model:
	rm -r ../../../data/output/gray_distribution/models

clean_output:
	rm -r ../../../data/output/gray_distribution/output

clean_log:
	rm -r ../../../data/output/gray_distribution/log

clean:
	rm -r ../../../data/output/gray_distribution