all:
	python train.py
	echo 'Trained ~!'

clean_model:
	rm -r ../../../data/output/dense/models

clean_output:
	rm -r ../../../data/output/dense/output

clean_log:
	rm -r ../../../data/output/dense/log

clean:
	rm -r ../../../data/output/dense